<?php
@define('_baiviet','Posts'); 
@define('_baivietkhac','Other article'); 
@define('_banphaikichhoat','You must activate your account before signing in'); 
@define('_binhluan','Comment'); 
@define('_capnhat','Update'); 
@define('_chitietsanpham','Product details'); 
@define('_chiduong','Direct'); 
@define('_chonvideo','Select a video'); 
@define('_chuacosanpham','No product'); 
@define('_chuacosanphamyeuthich','No favorite products yet'); 
@define('_danhmucsanpham','Product catalog'); 
@define('_dichvu','Service'); 
@define('_email','E-mail'); 
@define('_gia','Old'); 
@define('_giaban','Price'); 
@define('_giacu','Old price'); 
@define('_giakhuyenmai','Promotion price'); 
@define('_giohang','Cart'); 
@define('_gioithieu','Introduce'); 
@define('_about','Introduce'); 
@define('_goidien','Call'); 
@define('_gui','Sends'); 
@define('_guidonhang','Submit an order'); 
@define('_hinhanh','Picture'); 
@define('_name','Full name'); 
@define('_hotrotructuyen','online support'); 
@define('_hovaten','First and last name'); 
@define('_hoac','Or'); 
@define('_hoatdong','Activity'); 
@define('_homnay','Today'); 
@define('_huongdansudung','Manual instruction'); 
@define('_ketqua','Result'); 
@define('_kichhoattaikhoan','Active account'); 
@define('_lamlai','Rework, do it again'); 
@define('_lienhe','Contact'); 
@define('_luotxem','View'); 
@define('_masanpham','Product code'); 
@define('_pass','password'); 
@define('_matkhau','password'); 
@define('_mota','Describe'); 
@define('_muatiep','Buy next'); 
@define('_nhapemail','Enter Email ...'); 
@define('_confirm','Enter the password'); 
@define('_nhomatkhau','Remember password'); 
@define('_noidung','Say right'); 
@define('_noidungchitiet','details'); 
@define('_noidungchuacapnhat','Content not updated yet'); 
@define('_quenmatkhau','Forgot password'); 
@define('_sanpham','Product'); 
@define('_sanphamkhac','Other products'); 
@define('_sanphamlienquan','Related products'); 
@define('_sanphammoi','New product'); 
@define('_sanphamyeuthich','Favorite products'); 
@define('_soluong','Number'); 
@define('_stt','STT'); 
@define('_ten','Name'); 
@define('_tensanpham','Product&#39;s name'); 
@define('_tendangnhap','user name'); 
@define('_thongketruycap','Statistical access'); 
@define('_thongtinthanhvien','member information'); 
@define('_tieude','Title'); 
@define('_timkiem','Search'); 
@define('_timkiemsanpham','Search product'); 
@define('_timthay','Find'); 
@define('_tintuc','News'); 
@define('_tintuckhac','Other news'); 
@define('_tong','Total'); 
@define('_tonggia','total price'); 
@define('_tongtruycap','Total access'); 
@define('_trangchu','Home page'); 
@define('_tuannay','This week'); 
@define('_vechungtoi','About us'); 
@define('_xemthem','see more'); 
@define('_xinchao','Hello'); 
@define('_xoa','Erase'); 
@define('_xoakhoidanhsach','Remove from list'); 
@define('_ykienkhachhang','Customer reviews'); 
@define('_dangky','Register'); 
@define('_dangkynhantin','Sign up for'); 
@define('_dangnhap','Login'); 
@define('_dangnhapqua','Login via'); 
@define('_dangonline','Online'); 
@define('_dangxuat','Log out'); 
@define('_dathang','Order'); 
@define('_diachi','Address'); 
@define('_dienthoai','Phone'); 
?>