<?php
@define('_baiviet','Bài viết'); 
@define('_baivietkhac','Bài viết khác'); 
@define('_banphaikichhoat','Bạn phải kích hoạt tài khoản trước khi đăng nhập'); 
@define('_binhluan','Bình luận'); 
@define('_capnhat','Cập nhật'); 
@define('_chitietsanpham','Chi tiết sản phẩm'); 
@define('_chiduong','Chỉ đường'); 
@define('_chonvideo','Chọn video'); 
@define('_chuacosanpham','Chưa có sản phẩm'); 
@define('_chuacosanphamyeuthich','Chưa có sản phẩm yêu thích'); 
@define('_danhmucsanpham','Danh mục sản phẩm'); 
@define('_dichvu','Dịch vụ'); 
@define('_email','Email'); 
@define('_gia','Giá'); 
@define('_giaban','Giá bán'); 
@define('_giacu','Giá cũ'); 
@define('_giakhuyenmai','Giá khuyến mãi'); 
@define('_giohang','Giỏ hàng'); 
@define('_gioithieu','Giới thiệu'); 
@define('_about','Giới thiệu'); 
@define('_goidien','Gọi điện'); 
@define('_gui','Gửi'); 
@define('_guidonhang','Gửi đơn hàng'); 
@define('_hinhanh','Hình ảnh'); 
@define('_name','Họ tên'); 
@define('_hotrotructuyen','Hỗ trợ trực tuyến'); 
@define('_hovaten','Họ và tên'); 
@define('_hoac','Hoặc'); 
@define('_hoatdong','Hoạt động'); 
@define('_homnay','Hôm nay'); 
@define('_huongdansudung','Hướng dẫn sử dụng'); 
@define('_ketqua','Kết quả'); 
@define('_kichhoattaikhoan','Kích hoạt, tài khoản'); 
@define('_lamlai','Làm lại'); 
@define('_lienhe','Liên hệ'); 
@define('_luotxem','Lượt xem'); 
@define('_masanpham','Mã sản phẩm'); 
@define('_pass','Mật khẩu'); 
@define('_matkhau','Mật khẩu'); 
@define('_mota','Mô tả'); 
@define('_muatiep','Mua tiếp'); 
@define('_nhapemail','Nhập Email...'); 
@define('_confirm','Nhập lại mật khẩu'); 
@define('_nhomatkhau','Nhớ mật khẩu'); 
@define('_noidung','Nội dung'); 
@define('_noidungchitiet','Nội dung chi tiết'); 
@define('_noidungchuacapnhat','Nội dung chưa cập nhật'); 
@define('_quenmatkhau','Quên mật khẩu'); 
@define('_sanpham','Sản phẩm'); 
@define('_sanphamkhac','Sản phẩm khác'); 
@define('_sanphamlienquan','Sản phẩm liên quan'); 
@define('_sanphammoi','Sản phẩm mới'); 
@define('_sanphamyeuthich','Sản phẩm yêu thích'); 
@define('_soluong','Số lượng'); 
@define('_stt','STT'); 
@define('_ten','Tên'); 
@define('_tensanpham','Tên sản phẩm'); 
@define('_tendangnhap','Tên đăng nhập'); 
@define('_thongketruycap','Thống kê truy cập'); 
@define('_thongtinthanhvien','Thông tin thành viên'); 
@define('_tieude','Tiêu đề'); 
@define('_timkiem','Tìm kiếm'); 
@define('_timkiemsanpham','Tìm kiếm sản phẩm'); 
@define('_timthay','Tìm thấy'); 
@define('_tintuc','Tin tức'); 
@define('_tintuckhac','Tin tức khác'); 
@define('_tong','Tổng'); 
@define('_tonggia','Tổng giá'); 
@define('_tongtruycap','Tổng truy cập'); 
@define('_trangchu','Trang chủ'); 
@define('_tuannay','Tuần này'); 
@define('_vechungtoi','Về chúng tôi'); 
@define('_xemthem','Xem thêm'); 
@define('_xinchao','Xin chào'); 
@define('_xoa','Xóa'); 
@define('_xoakhoidanhsach','Xóa khỏi danh sách'); 
@define('_ykienkhachhang','Ý kiến khách hàng'); 
@define('_dangky','Đăng ký'); 
@define('_dangkynhantin','Đăng ký nhận tin'); 
@define('_dangnhap','Đăng nhập'); 
@define('_dangnhapqua','Đăng nhập qua'); 
@define('_dangonline','Đang online'); 
@define('_dangxuat','Đăng xuất'); 
@define('_dathang','Đặt hàng'); 
@define('_diachi','Địa chỉ'); 
@define('_dienthoai','Điện thoại'); 
?>